CREATE TABLE IF NOT EXISTS TB_TRANSACTION_TYPE (
    TRANSACTION_TYPE_ID INT PRIMARY KEY,
    TRANSACTION_TYPE_DESCRIPTION VARCHAR(200)
);

INSERT INTO
    TB_TRANSACTION_TYPE(TRANSACTION_TYPE_ID, TRANSACTION_TYPE_DESCRIPTION)
VALUES
    (NULL, 'COMPRA A VISTA'),
    (NULL, 'COMPRA PARCELADA'),
    (NULL, 'SAQUE'),
    (NULL, 'PAGAMENTO');