CREATE TABLE IF NOT EXISTS TB_TRANSACTION_TYPE (
    TRANSACTION_TYPE_ID SERIAL PRIMARY KEY,
    TRANSACTION_TYPE_DESCRIPTION VARCHAR(200)
);

INSERT INTO
    TB_TRANSACTION_TYPE( TRANSACTION_TYPE_DESCRIPTION)
VALUES
    ('COMPRA A VISTA'),
    ('COMPRA PARCELADA'),
    ('SAQUE'),
    ('PAGAMENTO');